### PR TITLE
Split reconstruction and KL loss, and log them as metrics

### PR DESCRIPTION
**Pull request by ben-heil**
This PR splits the vae loss into its two separate components, reconstruction and kl loss, so that they are both displayed during training. This also allows you to access them individually through the history variable.

No rush on reviewing this PR, I just posted the code here so I didn't forget I had it.

### CODE REVIEW

**Review by ajlee21 — COMMENTED** [review]
Couple of comments.

1. Can you update the `setup.py` file to version 0.6.1 so that I can deploy it after this change is merged in
2. Just want to confirm that you do not need to update `vae.py` plotting because I think that is just for saving the loss to file

**Comment by ben-heil** [comment]
> 2. Just want to confirm that you do not need to update `vae.py` plotting because I think that is just for saving the loss to file

Correct, I added the two pieces of the loss as metrics, but the VAE loss is still stored as `loss` in history to make sure everything is backwards compatible. If there's a script or something outside of the tests that you want me to run to make sure everything is working I can do that too

**Review by ajlee21 — APPROVED** [review]
I think if you're able to check that the test notebooks generate the two loss curves, then we're golden

Thank you for making this change

**Comment by ben-heil** [comment]
Yep, I ran the test notebooks and the train/val curves are still showing up like they used to.

No problem!

**Pull request merged**
